# Generated by Django 3.2.2 on 2021-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('parents', 'parents'), ('teacher', 'teacher'), ('admin', 'admin')], default='user', max_length=40, verbose_name='Роль'),
        ),
    ]
