# Generated by Django 2.2.6 on 2021-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('parents', 'parents'), ('teacher', 'teacher'), ('admin', 'admin')], default=[('user', 'user'), ('parents', 'parents'), ('teacher', 'teacher'), ('admin', 'admin')], max_length=40, verbose_name='Роль'),
        ),
    ]
