# Generated by Django 3.2 on 2021-05-01 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название класса')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count_students', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество учеников')),
                ('projector', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.CharField(max_length=100)),
                ('room', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Название кабинета')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, unique=True, verbose_name='Название организыции')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('number_lessons', models.PositiveIntegerField(max_length=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('smena', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Смена')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les', to='time_table.lessons')),
            ],
        ),
    ]
