# Generated by Django 2.2.6 on 2021-04-11 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import time_table.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Имя класса/группы')),
                ('count_students', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество учеников')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название кабинета')),
                ('count_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('specifications', models.CharField(db_index=True, default='', max_length=50, verbose_name='Спецификация кабинета')),
                ('projector', models.BooleanField(db_index=True, default=False, max_length=50, verbose_name='Наличие проектора')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название урока')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название организыции')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя класса/группы', models.CharField(db_index=True, max_length=50, unique=True, verbose_name=time_table.models.Class)),
                ('number_lessons', models.CharField(max_length=10, verbose_name='Номер урока')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='time_table.ClassRoom', verbose_name='Кабинет')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='time_table.Lessons', verbose_name='Название урока')),
            ],
        ),
    ]
