# Generated by Django 3.2 on 2021-05-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='class',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='time_table.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='class',
            name='time_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_table_class', to='time_table.timetable', verbose_name='Расписание класса'),
        ),
    ]
