# Generated by Django 3.2.2 on 2021-05-12 20:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_table', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество учеников')),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='room',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='teacher',
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='lessons_class',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='lessons',
        ),
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='time_table.timetable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='addr',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='', max_length=40, verbose_name='Дни недели'),
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.AddField(
            model_name='room',
            name='specofroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.specification'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='specoflesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.specification'),
        ),
        migrations.AddField(
            model_name='journal',
            name='less',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_table.lesson'),
        ),
        migrations.AddField(
            model_name='journal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couple',
            name='less',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.lesson'),
        ),
        migrations.AddField(
            model_name='couple',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.room'),
        ),
        migrations.AddField(
            model_name='couple',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='jurn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jurn', to='time_table.journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='para',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='time_table.couple'),
            preserve_default=False,
        ),
    ]
