# Generated by Django 2.2.6 on 2021-04-11 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_auto_20210411_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='count_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество учеников'),
        ),
    ]
