# Generated by Django 3.2.2 on 2021-05-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_auto_20210512_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='addr',
            field=models.TextField(max_length=255),
        ),
    ]
