# Generated by Django 3.2 on 2021-05-01 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_auto_20210501_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='number_lessons',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
