# Generated by Django 3.2.2 on 2021-05-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0004_alter_organization_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='specofroom',
            new_name='spec_of_room',
        ),
    ]
