# Generated by Django 3.2.2 on 2021-05-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0005_rename_specofroom_room_spec_of_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='specoflesson',
            new_name='spec_of_lesson',
        ),
    ]
