# Generated by Django 3.2.2 on 2021-05-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0007_alter_lesson_spec_of_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='spec_of_lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='time_table.specification'),
        ),
    ]
