# Generated by Django 3.2.2 on 2021-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0008_alter_lesson_spec_of_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
