# Generated by Django 3.2.2 on 2021-05-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0011_alter_lesson_spec_of_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec_of_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_table.specification'),
        ),
    ]
