# Generated by Django 3.2.2 on 2021-05-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0012_alter_room_spec_of_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'number_lessons'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.couple', verbose_name='Уроки'),
        ),
    ]
