# Generated by Django 3.2.2 on 2021-05-14 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_table', '0013_auto_20210514_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='учитель'),
        ),
    ]
