# Generated by Django 3.2.2 on 2021-05-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0014_alter_couple_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.couple'),
        ),
    ]
