# Generated by Django 3.2.2 on 2021-05-19 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_table', '0015_alter_timetable_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='jurn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurn', to='time_table.journal', verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='class',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='time_table.timetable', verbose_name='Расписание класса'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='less',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.lesson', verbose_name='Уроки'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.room', verbose_name='Кабинет'),
        ),
        migrations.RemoveField(
            model_name='couple',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='journal',
            name='less',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_table.lesson', verbose_name='Уроки'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='spec_of_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_table.specification', verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_org', to='time_table.class', verbose_name='Название классов'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='room',
            name='spec_of_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_table.specification', verbose_name='Спецификация кабинета'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название спецификации'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.couple', verbose_name='урок-класс-учитель'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_table.class', verbose_name='Классы')),
                ('spec_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_table.lesson', verbose_name='Специализация учителя')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учителя')),
            ],
        ),
        migrations.AddField(
            model_name='couple',
            name='teacher',
            field=models.ManyToManyField(to='time_table.Teacher', verbose_name='Учитель'),
        ),
    ]
