# Generated by Django 3.2.2 on 2021-05-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0017_alter_journal_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
    ]
