# Generated by Django 3.2.2 on 2021-05-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0019_alter_specification_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couple',
            new_name='Para',
        ),
    ]
