# Generated by Django 3.2.2 on 2021-05-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0020_rename_couple_para'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='jurn',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
