# Generated by Django 3.2.2 on 2021-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0021_auto_20210526_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='less',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_less', to='time_table.lesson', verbose_name='Уроки'),
        ),
    ]
