# Generated by Django 3.2.2 on 2021-06-10 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0022_class_less'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='day_lessons',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='number_lessons',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
